openapi: 3.0.0
info:
  title: "Your API Title"
  version: "1.0.0"
  description: "Description of your API"
servers:
  - url: http://localhost:3000/api
paths:
  $ref: ./paths/index.yaml  # Reference to paths

components:
  $ref: ./components/index.yaml # Reference to components