Product:
  type: object
  properties:
    productName:
      type: string
    stokeAmount:
      type: number
    buyingPrice:
      type: number
    sellingPrice:
      type: number
    categoryId:
      type: string
    productBrand:
      type: string
    unit:
      type: string
  required:
    - productName
    - stokeAmount
    - buyingPrice
    - categoryId
    - sellingPrice
    - productBrand
    - unit
    - categoryId

ProductResponse:
  type: object
  properties:
    success:
      type: boolean
    message:
      type: string
    product:
      type: object
      properties:
        productName:
          type: string
        stokeAmount:
          type: number
        buyingPrice:
          type: number
        sellingPrice:
          type: number
        productCategory:
          type: string
        productBrand:
          type: string
        unit:
          type: string

SingleProductResponse:
  type: object
  properties:
    success:
      type: boolean
    message:
      type: string
    product:
      type: object
      properties:
        qrcodeUrl:
          type: string
        productName:
          type: string
        stokeAmount:
          type: number
        buyingPrice:
          type: number
        sellingPrice:
          type: number
        productCategory:
          type: string
        productCategoryID:
          type: string
        productBrand:
          type: string
        unit:
          type: string
        shopOwnerId:
          type: string

ProductsResponse:
  type: object
  properties:
    success:
      type: boolean
    message:
      type: string
    products:
      type: array
      items:
        $ref: "#/components/schemas/Product"